local tooltiphelper_magnumopus = {
   misc_0139={
      {
         row=0,
         name="misc_0132",
         col=0
      },
      {
         row=0,
         name="misc_0132",
         col=1
      },
      {
         row=0,
         name="misc_0132",
         col=2
      },
      {
         row=1,
         name="misc_0132",
         col=0
      },
      {
         row=1,
         name="misc_0132",
         col=2
      },
      {
         row=2,
         name="misc_0132",
         col=0
      },
      {
         row=2,
         name="misc_0132",
         col=1
      },
      {
         row=2,
         name="misc_0132",
         col=2
      }
   },
   misc_icepiece={
      {
         row=0,
         name="Drug_holywater",
         col=0
      },
      {
         row=0,
         name="Drug_holywater",
         col=1
      },
      {
         row=1,
         name="Drug_holywater",
         col=0
      },
      {
         row=1,
         name="Drug_holywater",
         col=1
      }
   },
   misc_Spector_Gh={
      {
         row=0,
         name="misc_Corylus",
         col=0
      },
      {
         row=0,
         name="misc_Corylus",
         col=1
      },
      {
         row=1,
         name="misc_Corylus",
         col=0
      },
      {
         row=1,
         name="misc_Corylus",
         col=1
      }
   },
   misc_0064={
      {
         row=0,
         name="misc_0105",
         col=0
      },
      {
         row=0,
         name="misc_0105",
         col=1
      },
      {
         row=1,
         name="misc_0105",
         col=0
      },
      {
         row=1,
         name="misc_0105",
         col=1
      }
   },
   misc_goblin={
      {
         row=0,
         name="misc_Bume_Goblin",
         col=0
      },
      {
         row=0,
         name="misc_Bume_Goblin",
         col=1
      },
      {
         row=1,
         name="misc_Bume_Goblin",
         col=0
      },
      {
         row=1,
         name="misc_Bume_Goblin",
         col=1
      },
      {
         row=2,
         name="misc_Bume_Goblin",
         col=0
      },
      {
         row=2,
         name="misc_Bume_Goblin",
         col=1
      }
   },
   misc_Rubabos={
      {
         row=0,
         name="misc_0137",
         col=0
      },
      {
         row=0,
         name="misc_0137",
         col=1
      },
      {
         row=1,
         name="misc_0137",
         col=0
      },
      {
         row=1,
         name="misc_0137",
         col=1
      }
   },
   misc_Caro={
      {
         row=0,
         name="misc_maize",
         col=0
      },
      {
         row=0,
         name="misc_maize",
         col=1
      },
      {
         row=1,
         name="misc_maize",
         col=0
      },
      {
         row=1,
         name="misc_maize",
         col=1
      }
   },
   misc_zigri={
      {
         row=0,
         name="misc_puragi",
         col=0
      },
      {
         row=0,
         name="misc_puragi",
         col=1
      },
      {
         row=1,
         name="misc_puragi",
         col=0
      },
      {
         row=1,
         name="misc_puragi",
         col=1
      }
   },
   misc_yekubite3={
      {
         row=0,
         name="misc_yekubite2",
         col=0
      },
      {
         row=0,
         name="misc_yekubite2",
         col=1
      },
      {
         row=2,
         name="misc_yekubite2",
         col=1
      },
      {
         row=3,
         name="misc_yekubite2",
         col=1
      },
      {
         row=3,
         name="misc_yekubite2",
         col=2
      },
      {
         row=4,
         name="misc_yekubite2",
         col=1
      }
   },
   misc_chromadog={
      {
         row=0,
         name="misc_0129",
         col=0
      },
      {
         row=0,
         name="misc_0129",
         col=1
      },
      {
         row=1,
         name="misc_0129",
         col=0
      },
      {
         row=1,
         name="misc_0129",
         col=1
      }
   },
   misc_0026={
      {
         row=0,
         name="misc_zigri",
         col=0
      },
      {
         row=0,
         name="misc_zigri",
         col=1
      },
      {
         row=1,
         name="misc_zigri",
         col=0
      },
      {
         row=1,
         name="misc_zigri",
         col=1
      }
   },
   misc_Rambear={
      {
         row=0,
         name="misc_0179",
         col=0
      },
      {
         row=0,
         name="misc_0179",
         col=1
      },
      {
         row=1,
         name="misc_0179",
         col=0
      },
      {
         row=1,
         name="misc_0179",
         col=1
      }
   },
   misc_0103={
      {
         row=0,
         name="misc_0055",
         col=0
      },
      {
         row=1,
         name="misc_0055",
         col=1
      },
      {
         row=1,
         name="misc_0055",
         col=3
      },
      {
         row=2,
         name="misc_0055",
         col=2
      },
      {
         row=2,
         name="misc_0055",
         col=3
      },
      {
         row=3,
         name="misc_0055",
         col=2
      }
   },
   misc_0166={
      {
         row=0,
         name="misc_0144",
         col=0
      },
      {
         row=0,
         name="misc_0144",
         col=1
      },
      {
         row=1,
         name="misc_0144",
         col=2
      },
      {
         row=2,
         name="misc_0144",
         col=1
      },
      {
         row=3,
         name="misc_0144",
         col=1
      }
   },
   misc_0119={
      {
         row=0,
         name="misc_0109",
         col=0
      },
      {
         row=0,
         name="misc_0109",
         col=3
      },
      {
         row=1,
         name="misc_0109",
         col=1
      },
      {
         row=1,
         name="misc_0109",
         col=2
      },
      {
         row=2,
         name="misc_0109",
         col=0
      },
      {
         row=2,
         name="misc_0109",
         col=3
      }
   },
   misc_0184={
      {
         row=0,
         name="misc_Infroholder",
         col=0
      },
      {
         row=0,
         name="misc_Infroholder",
         col=1
      },
      {
         row=1,
         name="misc_Infroholder",
         col=0
      },
      {
         row=1,
         name="misc_Infroholder",
         col=1
      }
   },
   misc_0060={
      {
         row=0,
         name="misc_Dumaro",
         col=0
      },
      {
         row=0,
         name="misc_Dumaro",
         col=1
      },
      {
         row=1,
         name="misc_Dumaro",
         col=0
      },
      {
         row=1,
         name="misc_Dumaro",
         col=1
      }
   },
   misc_0061={
      {
         row=0,
         name="misc_Ticen",
         col=0
      },
      {
         row=0,
         name="misc_Ticen",
         col=1
      },
      {
         row=1,
         name="misc_Ticen",
         col=0
      },
      {
         row=1,
         name="misc_Ticen",
         col=1
      },
      {
         row=2,
         name="misc_Ticen",
         col=0
      },
      {
         row=2,
         name="misc_Ticen",
         col=1
      }
   },
   misc_0134={
      {
         row=0,
         name="misc_0131",
         col=0
      },
      {
         row=1,
         name="misc_0131",
         col=1
      },
      {
         row=1,
         name="misc_0131",
         col=3
      },
      {
         row=2,
         name="misc_0131",
         col=2
      },
      {
         row=2,
         name="misc_0131",
         col=3
      },
      {
         row=3,
         name="misc_0131",
         col=2
      }
   },
   misc_0244={
      {
         row=0,
         name="misc_0196",
         col=0
      },
      {
         row=0,
         name="misc_0196",
         col=2
      },
      {
         row=1,
         name="misc_0196",
         col=3
      },
      {
         row=2,
         name="misc_0196",
         col=4
      },
      {
         row=3,
         name="misc_0196",
         col=3
      },
      {
         row=4,
         name="misc_0196",
         col=1
      }
   },
   misc_0056={
      {
         row=0,
         name="misc_Ammon",
         col=0
      },
      {
         row=0,
         name="misc_Ammon",
         col=1
      },
      {
         row=1,
         name="misc_Ammon",
         col=0
      },
      {
         row=1,
         name="misc_Ammon",
         col=1
      }
   },
   misc_Bume_Goblin={
      {
         row=0,
         name="misc_0013",
         col=0
      },
      {
         row=0,
         name="misc_0013",
         col=1
      },
      {
         row=1,
         name="misc_0013",
         col=0
      },
      {
         row=1,
         name="misc_0013",
         col=1
      },
      {
         row=2,
         name="misc_0013",
         col=0
      },
      {
         row=2,
         name="misc_0013",
         col=1
      }
   },
   misc_0094={
      {
         row=0,
         name="misc_0065",
         col=0
      },
      {
         row=0,
         name="misc_0065",
         col=1
      },
      {
         row=1,
         name="misc_0065",
         col=0
      },
      {
         row=1,
         name="misc_0065",
         col=1
      }
   },
   TSF02_105={
      {
         row=0,
         name="misc_ore09",
         col=0
      },
      {
         row=1,
         name="misc_ore09",
         col=0
      },
      {
         row=2,
         name="misc_ore09",
         col=0
      },
      {
         row=3,
         name="misc_ore09",
         col=0
      },
      {
         row=4,
         name="misc_ore09",
         col=0
      },
      {
         row=5,
         name="misc_ore09",
         col=0
      }
   },
   misc_Ticen={
      {
         row=0,
         name="misc_0058",
         col=0
      },
      {
         row=0,
         name="misc_0058",
         col=1
      },
      {
         row=1,
         name="misc_0058",
         col=0
      },
      {
         row=1,
         name="misc_0058",
         col=1
      }
   },
   misc_humming_bud={
      {
         row=0,
         name="misc_leafly",
         col=0
      },
      {
         row=0,
         name="misc_leafly",
         col=1
      },
      {
         row=0,
         name="misc_leafly",
         col=3
      },
      {
         row=1,
         name="misc_leafly",
         col=0
      },
      {
         row=1,
         name="misc_leafly",
         col=1
      },
      {
         row=1,
         name="misc_leafly",
         col=3
      }
   },
   misc_Ammon={
      {
         row=0,
         name="misc_0102",
         col=0
      },
      {
         row=0,
         name="misc_0102",
         col=1
      },
      {
         row=1,
         name="misc_0102",
         col=0
      },
      {
         row=1,
         name="misc_0102",
         col=1
      }
   },
   misc_ellomago={
      {
         row=0,
         name="misc_Bushspider_purple",
         col=0
      },
      {
         row=0,
         name="misc_Bushspider_purple",
         col=1
      },
      {
         row=1,
         name="misc_Bushspider_purple",
         col=0
      },
      {
         row=1,
         name="misc_Bushspider_purple",
         col=1
      }
   },
   misc_Haming2={
      {
         row=0,
         name="misc_Tontulia",
         col=0
      },
      {
         row=0,
         name="misc_Tontulia",
         col=1
      },
      {
         row=1,
         name="misc_Tontulia",
         col=0
      }
   },
   misc_0133={
      {
         row=0,
         name="misc_minivern",
         col=0
      },
      {
         row=0,
         name="misc_minivern",
         col=1
      },
      {
         row=1,
         name="misc_minivern",
         col=0
      },
      {
         row=1,
         name="misc_minivern",
         col=1
      }
   },
   misc_0140={
      {
         row=0,
         name="misc_Repusbunny",
         col=0
      },
      {
         row=0,
         name="misc_Repusbunny",
         col=1
      },
      {
         row=1,
         name="misc_Repusbunny",
         col=0
      },
      {
         row=1,
         name="misc_Repusbunny",
         col=1
      }
   },
   misc_Fire_Dragon2={
      {
         row=0,
         name="misc_0079",
         col=0
      },
      {
         row=0,
         name="misc_0079",
         col=1
      },
      {
         row=2,
         name="misc_0079",
         col=1
      },
      {
         row=3,
         name="misc_0079",
         col=1
      },
      {
         row=3,
         name="misc_0079",
         col=2
      },
      {
         row=3,
         name="misc_0079",
         col=5
      }
   },
   misc_0011={
      {
         row=0,
         name="OnionPiece_Red",
         col=0
      },
      {
         row=0,
         name="OnionPiece_Red",
         col=2
      },
      {
         row=1,
         name="OnionPiece_Red",
         col=1
      },
      {
         row=2,
         name="OnionPiece_Red",
         col=0
      },
      {
         row=2,
         name="OnionPiece_Red",
         col=2
      }
   },
   misc_Corylus={
      {
         row=0,
         name="misc_Caro",
         col=0
      },
      {
         row=1,
         name="misc_Caro",
         col=0
      },
      {
         row=2,
         name="misc_Caro",
         col=0
      },
      {
         row=3,
         name="misc_Caro",
         col=0
      }
   },
   misc_0025={
      {
         row=0,
         name="misc_0026",
         col=0
      },
      {
         row=0,
         name="misc_0026",
         col=1
      },
      {
         row=1,
         name="misc_0026",
         col=0
      },
      {
         row=1,
         name="misc_0026",
         col=1
      }
   },
   misc_0112={
      {
         row=0,
         name="misc_seedmia",
         col=0
      },
      {
         row=1,
         name="misc_seedmia",
         col=0
      },
      {
         row=2,
         name="misc_seedmia",
         col=0
      }
   },
   misc_0019={
      {
         row=0,
         name="misc_0015",
         col=0
      },
      {
         row=0,
         name="misc_0015",
         col=1
      },
      {
         row=1,
         name="misc_0015",
         col=0
      },
      {
         row=1,
         name="misc_0015",
         col=1
      }
   },
   misc_glizardon={
      {
         row=0,
         name="misc_0018",
         col=0
      },
      {
         row=0,
         name="misc_0018",
         col=1
      },
      {
         row=1,
         name="misc_0018",
         col=0
      },
      {
         row=1,
         name="misc_0018",
         col=1
      },
      {
         row=2,
         name="misc_0018",
         col=0
      },
      {
         row=2,
         name="misc_0018",
         col=1
      }
   },
   misc_0155={
      {
         row=0,
         name="misc_0152",
         col=0
      },
      {
         row=1,
         name="misc_0152",
         col=1
      },
      {
         row=1,
         name="misc_0152",
         col=3
      },
      {
         row=2,
         name="misc_0152",
         col=2
      },
      {
         row=2,
         name="misc_0152",
         col=3
      },
      {
         row=3,
         name="misc_0152",
         col=2
      }
   },
   misc_0144={
      {
         row=0,
         name="misc_0080",
         col=0
      },
      {
         row=0,
         name="misc_0080",
         col=1
      },
      {
         row=1,
         name="misc_0080",
         col=2
      },
      {
         row=2,
         name="misc_0080",
         col=1
      },
      {
         row=3,
         name="misc_0080",
         col=1
      }
   },
   misc_0086={
      {
         row=0,
         name="misc_chromadog",
         col=0
      },
      {
         row=0,
         name="misc_chromadog",
         col=1
      },
      {
         row=1,
         name="misc_chromadog",
         col=0
      },
      {
         row=1,
         name="misc_chromadog",
         col=1
      }
   },
   misc_0162={
      {
         row=0,
         name="misc_0141",
         col=0
      },
      {
         row=0,
         name="misc_0141",
         col=1
      },
      {
         row=0,
         name="misc_0141",
         col=2
      },
      {
         row=1,
         name="misc_0141",
         col=0
      },
      {
         row=1,
         name="misc_0141",
         col=2
      },
      {
         row=2,
         name="misc_0141",
         col=0
      },
      {
         row=2,
         name="misc_0141",
         col=1
      },
      {
         row=2,
         name="misc_0141",
         col=2
      }
   },
   misc_0136={
      {
         row=0,
         name="misc_0086",
         col=0
      },
      {
         row=1,
         name="misc_0086",
         col=0
      },
      {
         row=1,
         name="misc_0086",
         col=1
      },
      {
         row=2,
         name="misc_0086",
         col=0
      }
   },
   misc_0058={
      {
         row=0,
         name="misc_0135",
         col=0
      },
      {
         row=0,
         name="misc_0135",
         col=1
      },
      {
         row=1,
         name="misc_0135",
         col=0
      },
      {
         row=1,
         name="misc_0135",
         col=1
      },
      {
         row=2,
         name="misc_0135",
         col=0
      }
   },
   misc_0275={
      {
         row=0,
         name="misc_0269",
         col=0
      },
      {
         row=1,
         name="misc_0269",
         col=1
      },
      {
         row=1,
         name="misc_0269",
         col=3
      },
      {
         row=2,
         name="misc_0269",
         col=2
      },
      {
         row=2,
         name="misc_0269",
         col=3
      },
      {
         row=3,
         name="misc_0269",
         col=2
      }
   },
   misc_0055={
      {
         row=0,
         name="misc_0047",
         col=0
      },
      {
         row=1,
         name="misc_0047",
         col=1
      },
      {
         row=1,
         name="misc_0047",
         col=3
      },
      {
         row=2,
         name="misc_0047",
         col=2
      },
      {
         row=2,
         name="misc_0047",
         col=3
      },
      {
         row=3,
         name="misc_0047",
         col=2
      }
   },
   misc_0106={
      {
         row=0,
         name="misc_0005",
         col=0
      },
      {
         row=1,
         name="misc_0005",
         col=0
      },
      {
         row=2,
         name="misc_0005",
         col=0
      },
      {
         row=3,
         name="misc_0005",
         col=0
      }
   },
   misc_Karas={
      {
         row=0,
         name="misc_Dumaro",
         col=0
      },
      {
         row=0,
         name="misc_Dumaro",
         col=1
      },
      {
         row=1,
         name="misc_Dumaro",
         col=0
      },
      {
         row=1,
         name="misc_Dumaro",
         col=1
      },
      {
         row=2,
         name="misc_Dumaro",
         col=0
      },
      {
         row=2,
         name="misc_Dumaro",
         col=1
      }
   },
   misc_whip_vine_ra2={
      {
         row=0,
         name="misc_popolion3",
         col=0
      },
      {
         row=0,
         name="misc_popolion3",
         col=1
      },
      {
         row=0,
         name="misc_popolion3",
         col=2
      },
      {
         row=0,
         name="misc_popolion3",
         col=3
      }
   },
   misc_0237={
      {
         row=0,
         name="misc_0236",
         col=0
      },
      {
         row=0,
         name="misc_0236",
         col=1
      },
      {
         row=0,
         name="misc_0236",
         col=3
      },
      {
         row=1,
         name="misc_0236",
         col=2
      },
      {
         row=2,
         name="misc_0236",
         col=1
      },
      {
         row=2,
         name="misc_0236",
         col=3
      },
      {
         row=3,
         name="misc_0236",
         col=1
      },
      {
         row=3,
         name="misc_0236",
         col=2
      }
   },
   misc_shtayim={
      {
         row=0,
         name="misc_0064",
         col=0
      },
      {
         row=0,
         name="misc_0064",
         col=1
      },
      {
         row=1,
         name="misc_0064",
         col=0
      },
      {
         row=1,
         name="misc_0064",
         col=1
      }
   },
   misc_0234={
      {
         row=0,
         name="misc_0231",
         col=0
      },
      {
         row=0,
         name="misc_0231",
         col=1
      },
      {
         row=2,
         name="misc_0231",
         col=1
      },
      {
         row=3,
         name="misc_0231",
         col=1
      },
      {
         row=3,
         name="misc_0231",
         col=2
      },
      {
         row=4,
         name="misc_0231",
         col=1
      }
   },
   misc_0014={
      {
         row=0,
         name="misc_0119",
         col=0
      },
      {
         row=0,
         name="misc_0119",
         col=1
      },
      {
         row=1,
         name="misc_0119",
         col=0
      },
      {
         row=1,
         name="misc_0119",
         col=1
      }
   },
   misc_0129={
      {
         row=0,
         name="misc_0127",
         col=0
      },
      {
         row=1,
         name="misc_0127",
         col=0
      },
      {
         row=2,
         name="misc_0127",
         col=0
      },
      {
         row=3,
         name="misc_0127",
         col=0
      }
   },
   misc_banshee={
      {
         row=0,
         name="misc_0018",
         col=0
      },
      {
         row=0,
         name="misc_0018",
         col=1
      },
      {
         row=1,
         name="misc_0018",
         col=0
      },
      {
         row=1,
         name="misc_0018",
         col=1
      }
   },
   misc_0074={
      {
         row=0,
         name="misc_0139",
         col=0
      },
      {
         row=0,
         name="misc_0139",
         col=1
      },
      {
         row=1,
         name="misc_0139",
         col=0
      },
      {
         row=1,
         name="misc_0139",
         col=1
      }
   },
   food_Popolion={
      {
         row=0,
         name="misc_0001",
         col=0
      },
      {
         row=0,
         name="misc_0001",
         col=1
      },
      {
         row=1,
         name="misc_0001",
         col=0
      },
      {
         row=1,
         name="misc_0001",
         col=1
      }
   },
   misc_0006={
      {
         row=0,
         name="misc_0002",
         col=0
      },
      {
         row=0,
         name="misc_0002",
         col=1
      },
      {
         row=1,
         name="misc_0002",
         col=0
      },
      {
         row=1,
         name="misc_0002",
         col=1
      }
   },
   misc_0072={
      {
         row=0,
         name="misc_0054",
         col=0
      },
      {
         row=0,
         name="misc_0054",
         col=1
      },
      {
         row=1,
         name="misc_0054",
         col=2
      },
      {
         row=2,
         name="misc_0054",
         col=1
      },
      {
         row=3,
         name="misc_0054",
         col=1
      }
   },
   rsc_2_1={
      {
         row=0,
         name="misc_mud",
         col=0
      },
      {
         row=1,
         name="misc_mud",
         col=1
      },
      {
         row=2,
         name="misc_mud",
         col=0
      },
      {
         row=2,
         name="misc_mud",
         col=1
      },
      {
         row=2,
         name="misc_mud",
         col=2
      }
   },
   misc_0225={
      {
         row=0,
         name="misc_0162",
         col=0
      },
      {
         row=0,
         name="misc_0162",
         col=1
      },
      {
         row=0,
         name="misc_0162",
         col=2
      },
      {
         row=1,
         name="misc_0162",
         col=0
      },
      {
         row=1,
         name="misc_0162",
         col=2
      },
      {
         row=2,
         name="misc_0162",
         col=0
      },
      {
         row=2,
         name="misc_0162",
         col=1
      },
      {
         row=2,
         name="misc_0162",
         col=2
      }
   },
   misc_Rudas_loxodon={
      {
         row=0,
         name="misc_mallardu",
         col=0
      },
      {
         row=0,
         name="misc_mallardu",
         col=1
      },
      {
         row=1,
         name="misc_mallardu",
         col=0
      },
      {
         row=1,
         name="misc_mallardu",
         col=1
      }
   },
   misc_mallardu={
      {
         row=0,
         name="food_Popolion",
         col=0
      },
      {
         row=0,
         name="food_Popolion",
         col=1
      },
      {
         row=0,
         name="food_Popolion",
         col=3
      },
      {
         row=1,
         name="food_Popolion",
         col=0
      },
      {
         row=1,
         name="food_Popolion",
         col=1
      },
      {
         row=1,
         name="food_Popolion",
         col=3
      }
   },
   misc_0097={
      {
         row=0,
         name="misc_0093",
         col=0
      },
      {
         row=1,
         name="misc_0093",
         col=0
      },
      {
         row=2,
         name="misc_0093",
         col=0
      },
      {
         row=2,
         name="misc_0093",
         col=1
      }
   },
   misc_liena_pants_1={
      {
         row=0,
         name="misc_0135",
         col=0
      },
      {
         row=0,
         name="misc_0135",
         col=1
      },
      {
         row=1,
         name="misc_0135",
         col=1
      },
      {
         row=2,
         name="misc_0135",
         col=1
      },
      {
         row=3,
         name="misc_0135",
         col=0
      },
      {
         row=3,
         name="misc_0135",
         col=2
      }
   },
   misc_0137={
      {
         row=0,
         name="misc_minivern",
         col=0
      },
      {
         row=0,
         name="misc_minivern",
         col=1
      },
      {
         row=1,
         name="misc_minivern",
         col=0
      },
      {
         row=1,
         name="misc_minivern",
         col=1
      },
      {
         row=2,
         name="misc_minivern",
         col=0
      },
      {
         row=2,
         name="misc_minivern",
         col=1
      }
   },
   misc_schlesien_darkmage={
      {
         row=0,
         name="misc_0104",
         col=0
      },
      {
         row=0,
         name="misc_0104",
         col=1
      },
      {
         row=1,
         name="misc_0104",
         col=0
      },
      {
         row=1,
         name="misc_0104",
         col=1
      }
   },
   misc_seedOil={
      {
         row=0,
         name="misc_seedmia",
         col=0
      },
      {
         row=1,
         name="misc_seedmia",
         col=1
      },
      {
         row=2,
         name="misc_seedmia",
         col=2
      }
   },
   misc_minivern={
      {
         row=0,
         name="misc_0080",
         col=0
      },
      {
         row=0,
         name="misc_0080",
         col=1
      },
      {
         row=1,
         name="misc_0080",
         col=0
      },
      {
         row=1,
         name="misc_0080",
         col=1
      }
   },
   misc_talt={
      {
         row=0,
         name="misc_goldbar",
         col=0
      },
      {
         row=3,
         name="misc_goldbar",
         col=3
      }
   },
   STF02_107={
      {
         row=0,
         name="misc_ore09",
         col=0
      },
      {
         row=0,
         name="misc_ore09",
         col=1
      },
      {
         row=1,
         name="misc_ore09",
         col=1
      },
      {
         row=2,
         name="misc_ore09",
         col=1
      },
      {
         row=3,
         name="misc_ore09",
         col=1
      }
   },
   misc_goldbar={
      {
         row=0,
         name="misc_talt",
         col=0
      },
      {
         row=0,
         name="misc_talt",
         col=1
      },
      {
         row=1,
         name="misc_talt",
         col=0
      },
      {
         row=1,
         name="misc_talt",
         col=1
      },
      {
         row=2,
         name="misc_talt",
         col=0
      },
      {
         row=2,
         name="misc_talt",
         col=1
      },
      {
         row=3,
         name="misc_talt",
         col=0
      },
      {
         row=3,
         name="misc_talt",
         col=1
      },
      {
         row=4,
         name="misc_talt",
         col=0
      },
      {
         row=4,
         name="misc_talt",
         col=1
      }
   },
   misc_0201={
      {
         row=0,
         name="misc_0028",
         col=0
      },
      {
         row=0,
         name="misc_0028",
         col=1
      },
      {
         row=1,
         name="misc_0028",
         col=2
      },
      {
         row=2,
         name="misc_0028",
         col=1
      },
      {
         row=3,
         name="misc_0028",
         col=1
      }
   },
   misc_0232={
      {
         row=0,
         name="misc_0229",
         col=0
      },
      {
         row=0,
         name="misc_0229",
         col=1
      },
      {
         row=0,
         name="misc_0229",
         col=3
      },
      {
         row=1,
         name="misc_0229",
         col=2
      },
      {
         row=2,
         name="misc_0229",
         col=1
      },
      {
         row=2,
         name="misc_0229",
         col=3
      },
      {
         row=3,
         name="misc_0229",
         col=1
      },
      {
         row=3,
         name="misc_0229",
         col=2
      }
   },
   egg_008={
      {
         row=0,
         name="misc_quicksilver",
         col=0
      },
      {
         row=0,
         name="misc_0011",
         col=1
      },
      {
         row=0,
         name="misc_0236",
         col=2
      },
      {
         row=1,
         name="misc_whip_vine_ra2",
         col=2
      },
      {
         row=1,
         name="misc_0244",
         col=3
      },
      {
         row=1,
         name="misc_yekubite3",
         col=4
      },
      {
         row=2,
         name="misc_Fire_Dragon2",
         col=3
      },
      {
         row=3,
         name="misc_goldbar",
         col=3
      },
      {
         row=4,
         name="misc_talt",
         col=2
      },
      {
         row=4,
         name="misc_seedOil",
         col=3
      },
      {
         row=4,
         name="misc_hanaming2",
         col=4
      },
      {
         row=6,
         name="misc_Dumaro",
         col=1
      },
      {
         row=6,
         name="misc_liena_pants_1",
         col=3
      },
      {
         row=6,
         name="rsc_2_1",
         col=5
      },
      {
         row=6,
         name="misc_icepiece",
         col=7
      }
   },
   misc_0113={
      {
         row=0,
         name="misc_banshee",
         col=0
      },
      {
         row=0,
         name="misc_banshee",
         col=1
      },
      {
         row=1,
         name="misc_banshee",
         col=0
      },
      {
         row=1,
         name="misc_banshee",
         col=1
      }
   },
   misc_0271={
      {
         row=0,
         name="misc_0268",
         col=0
      },
      {
         row=0,
         name="misc_0268",
         col=1
      },
      {
         row=2,
         name="misc_0268",
         col=1
      },
      {
         row=3,
         name="misc_0268",
         col=1
      },
      {
         row=3,
         name="misc_0268",
         col=2
      },
      {
         row=4,
         name="misc_0268",
         col=1
      }
   },
   misc_0163={
      {
         row=0,
         name="misc_0168",
         col=0
      },
      {
         row=0,
         name="misc_0168",
         col=1
      },
      {
         row=1,
         name="misc_0168",
         col=0
      },
      {
         row=1,
         name="misc_0168",
         col=1
      }
   },
   misc_0268={
      {
         row=0,
         name="misc_0247",
         col=0
      },
      {
         row=0,
         name="misc_0247",
         col=1
      },
      {
         row=2,
         name="misc_0247",
         col=1
      },
      {
         row=3,
         name="misc_0247",
         col=1
      },
      {
         row=3,
         name="misc_0247",
         col=2
      },
      {
         row=4,
         name="misc_0247",
         col=1
      }
   },
   misc_0247={
      {
         row=0,
         name="misc_0246",
         col=0
      },
      {
         row=0,
         name="misc_0246",
         col=1
      },
      {
         row=2,
         name="misc_0246",
         col=1
      },
      {
         row=3,
         name="misc_0246",
         col=1
      },
      {
         row=3,
         name="misc_0246",
         col=2
      },
      {
         row=4,
         name="misc_0246",
         col=1
      }
   },
   misc_0246={
      {
         row=0,
         name="misc_0234",
         col=0
      },
      {
         row=0,
         name="misc_0234",
         col=1
      },
      {
         row=2,
         name="misc_0234",
         col=1
      },
      {
         row=3,
         name="misc_0234",
         col=1
      },
      {
         row=3,
         name="misc_0234",
         col=2
      },
      {
         row=4,
         name="misc_0234",
         col=1
      }
   },
   misc_0135={
      {
         row=0,
         name="misc_Ammon",
         col=0
      },
      {
         row=0,
         name="misc_Ammon",
         col=1
      },
      {
         row=1,
         name="misc_Ammon",
         col=0
      },
      {
         row=1,
         name="misc_Ammon",
         col=1
      },
      {
         row=2,
         name="misc_Ammon",
         col=0
      },
      {
         row=2,
         name="misc_Ammon",
         col=1
      }
   },
   misc_0173={
      {
         row=0,
         name="misc_0148",
         col=0
      },
      {
         row=0,
         name="misc_0148",
         col=1
      },
      {
         row=0,
         name="misc_0148",
         col=2
      },
      {
         row=1,
         name="misc_0148",
         col=0
      },
      {
         row=1,
         name="misc_0148",
         col=1
      },
      {
         row=1,
         name="misc_0148",
         col=2
      }
   },
   misc_0054={
      {
         row=0,
         name="misc_0027",
         col=0
      },
      {
         row=0,
         name="misc_0027",
         col=1
      },
      {
         row=1,
         name="misc_0027",
         col=2
      },
      {
         row=2,
         name="misc_0027",
         col=1
      },
      {
         row=3,
         name="misc_0027",
         col=1
      }
   },
   misc_0045={
      {
         row=0,
         name="misc_0122",
         col=0
      },
      {
         row=0,
         name="misc_0122",
         col=1
      },
      {
         row=1,
         name="misc_0122",
         col=0
      },
      {
         row=1,
         name="misc_0122",
         col=1
      }
   },
   misc_0235={
      {
         row=0,
         name="misc_0221",
         col=0
      },
      {
         row=0,
         name="misc_0221",
         col=3
      },
      {
         row=1,
         name="misc_0221",
         col=1
      },
      {
         row=1,
         name="misc_0221",
         col=2
      },
      {
         row=2,
         name="misc_0221",
         col=0
      },
      {
         row=2,
         name="misc_0221",
         col=3
      }
   },
   misc_0231={
      {
         row=0,
         name="misc_0218",
         col=0
      },
      {
         row=0,
         name="misc_0218",
         col=1
      },
      {
         row=2,
         name="misc_0218",
         col=1
      },
      {
         row=3,
         name="misc_0218",
         col=1
      },
      {
         row=3,
         name="misc_0218",
         col=2
      },
      {
         row=4,
         name="misc_0218",
         col=1
      }
   },
   misc_0127={
      {
         row=0,
         name="misc_0074",
         col=0
      },
      {
         row=0,
         name="misc_0074",
         col=1
      },
      {
         row=1,
         name="misc_0074",
         col=0
      },
      {
         row=1,
         name="misc_0074",
         col=1
      }
   },
   tree_root_mole1={
      {
         row=0,
         name="misc_0165",
         col=0
      },
      {
         row=0,
         name="misc_0165",
         col=1
      },
      {
         row=1,
         name="misc_0165",
         col=0
      },
      {
         row=1,
         name="misc_0165",
         col=1
      }
   },
   misc_0210={
      {
         row=0,
         name="misc_0192",
         col=0
      },
      {
         row=0,
         name="misc_0192",
         col=1
      },
      {
         row=2,
         name="misc_0192",
         col=1
      },
      {
         row=3,
         name="misc_0192",
         col=1
      },
      {
         row=3,
         name="misc_0192",
         col=2
      },
      {
         row=4,
         name="misc_0192",
         col=1
      }
   },
   misc_0176={
      {
         row=0,
         name="misc_0166",
         col=0
      },
      {
         row=0,
         name="misc_0166",
         col=1
      },
      {
         row=1,
         name="misc_0166",
         col=2
      },
      {
         row=2,
         name="misc_0166",
         col=1
      },
      {
         row=3,
         name="misc_0166",
         col=1
      }
   },
   misc_Bushspider_purple={
      {
         row=0,
         name="misc_Cockatries",
         col=0
      },
      {
         row=0,
         name="misc_Cockatries",
         col=1
      },
      {
         row=1,
         name="misc_Cockatries",
         col=0
      },
      {
         row=1,
         name="misc_Cockatries",
         col=1
      }
   },
   misc_0192={
      {
         row=0,
         name="misc_0159",
         col=0
      },
      {
         row=0,
         name="misc_0159",
         col=1
      },
      {
         row=2,
         name="misc_0159",
         col=1
      },
      {
         row=3,
         name="misc_0159",
         col=1
      },
      {
         row=3,
         name="misc_0159",
         col=2
      },
      {
         row=4,
         name="misc_0159",
         col=1
      }
   },
   misc_maize={
      {
         row=0,
         name="misc_0113",
         col=0
      },
      {
         row=0,
         name="misc_0113",
         col=1
      },
      {
         row=1,
         name="misc_0113",
         col=0
      },
      {
         row=1,
         name="misc_0113",
         col=1
      }
   },
   misc_leafly={
      {
         row=0,
         name="misc_0119",
         col=0
      },
      {
         row=0,
         name="misc_0119",
         col=1
      },
      {
         row=0,
         name="misc_0119",
         col=2
      },
      {
         row=1,
         name="misc_0119",
         col=0
      }
   },
   misc_0159={
      {
         row=0,
         name="misc_0102",
         col=0
      },
      {
         row=0,
         name="misc_0102",
         col=1
      },
      {
         row=2,
         name="misc_0102",
         col=1
      },
      {
         row=3,
         name="misc_0102",
         col=1
      },
      {
         row=3,
         name="misc_0102",
         col=2
      },
      {
         row=4,
         name="misc_0102",
         col=1
      }
   },
   misc_Repusbunny={
      {
         row=0,
         name="misc_0153",
         col=0
      },
      {
         row=0,
         name="misc_0153",
         col=1
      },
      {
         row=1,
         name="misc_0153",
         col=0
      },
      {
         row=1,
         name="misc_0153",
         col=1
      }
   },
   misc_Velwriggler={
      {
         row=0,
         name="misc_Spector_Gh",
         col=0
      },
      {
         row=1,
         name="misc_Spector_Gh",
         col=0
      },
      {
         row=2,
         name="misc_Spector_Gh",
         col=0
      },
      {
         row=3,
         name="misc_Spector_Gh",
         col=0
      }
   },
   misc_Infroholder={
      {
         row=0,
         name="misc_chromadog",
         col=0
      },
      {
         row=1,
         name="misc_chromadog",
         col=0
      },
      {
         row=2,
         name="misc_chromadog",
         col=0
      },
      {
         row=3,
         name="misc_chromadog",
         col=0
      }
   },
   misc_0040={
      {
         row=0,
         name="misc_0035",
         col=0
      },
      {
         row=0,
         name="misc_0035",
         col=1
      },
      {
         row=1,
         name="misc_0035",
         col=0
      },
      {
         row=1,
         name="misc_0035",
         col=1
      }
   },
   misc_0046={
      {
         row=0,
         name="misc_0025",
         col=0
      },
      {
         row=0,
         name="misc_0025",
         col=1
      },
      {
         row=0,
         name="misc_0025",
         col=2
      },
      {
         row=1,
         name="misc_0025",
         col=0
      },
      {
         row=1,
         name="misc_0025",
         col=1
      },
      {
         row=1,
         name="misc_0025",
         col=2
      }
   },
   Hat_628047={
      {
         row=0,
         name="misc_goldbar",
         col=1
      },
      {
         row=0,
         name="misc_goldbar",
         col=2
      },
      {
         row=1,
         name="misc_goldbar",
         col=0
      },
      {
         row=1,
         name="misc_goldbar",
         col=1
      },
      {
         row=1,
         name="misc_goldbar",
         col=2
      },
      {
         row=1,
         name="misc_goldbar",
         col=3
      }
   },
   misc_0208={
      {
         row=0,
         name="misc_0177",
         col=0
      },
      {
         row=0,
         name="misc_0177",
         col=1
      },
      {
         row=1,
         name="misc_0177",
         col=2
      },
      {
         row=2,
         name="misc_0177",
         col=1
      },
      {
         row=3,
         name="misc_0177",
         col=1
      }
   },
   misc_0177={
      {
         row=0,
         name="misc_0175",
         col=0
      },
      {
         row=0,
         name="misc_0175",
         col=1
      },
      {
         row=1,
         name="misc_0175",
         col=2
      },
      {
         row=2,
         name="misc_0175",
         col=1
      },
      {
         row=3,
         name="misc_0175",
         col=1
      }
   },
   misc_0218={
      {
         row=0,
         name="misc_0215",
         col=0
      },
      {
         row=0,
         name="misc_0215",
         col=1
      },
      {
         row=2,
         name="misc_0215",
         col=1
      },
      {
         row=3,
         name="misc_0215",
         col=1
      },
      {
         row=3,
         name="misc_0215",
         col=2
      },
      {
         row=4,
         name="misc_0215",
         col=1
      }
   },
   misc_0028={
      {
         row=0,
         name="misc_0022",
         col=0
      },
      {
         row=0,
         name="misc_0022",
         col=1
      },
      {
         row=1,
         name="misc_0022",
         col=2
      },
      {
         row=2,
         name="misc_0022",
         col=1
      },
      {
         row=3,
         name="misc_0022",
         col=1
      }
   },
   misc_Dumaro={
      {
         row=0,
         name="misc_0046",
         col=0
      },
      {
         row=0,
         name="misc_0046",
         col=1
      },
      {
         row=0,
         name="misc_0046",
         col=2
      },
      {
         row=1,
         name="misc_0046",
         col=0
      },
      {
         row=1,
         name="misc_0046",
         col=1
      },
      {
         row=1,
         name="misc_0046",
         col=2
      }
   },
   misc_0270={
      {
         row=0,
         name="misc_0266",
         col=0
      },
      {
         row=0,
         name="misc_0266",
         col=1
      },
      {
         row=1,
         name="misc_0266",
         col=2
      },
      {
         row=2,
         name="misc_0266",
         col=1
      },
      {
         row=3,
         name="misc_0266",
         col=1
      }
   },
   misc_0266={
      {
         row=0,
         name="misc_0216",
         col=0
      },
      {
         row=0,
         name="misc_0216",
         col=1
      },
      {
         row=1,
         name="misc_0216",
         col=2
      },
      {
         row=2,
         name="misc_0216",
         col=1
      },
      {
         row=3,
         name="misc_0216",
         col=1
      }
   },
   misc_0070={
      {
         row=0,
         name="misc_0093",
         col=0
      },
      {
         row=0,
         name="misc_0093",
         col=1
      },
      {
         row=1,
         name="misc_0093",
         col=0
      },
      {
         row=1,
         name="misc_0093",
         col=1
      }
   },
   misc_0131={
      {
         row=0,
         name="misc_0128",
         col=0
      },
      {
         row=1,
         name="misc_0128",
         col=1
      },
      {
         row=1,
         name="misc_0128",
         col=3
      },
      {
         row=2,
         name="misc_0128",
         col=2
      },
      {
         row=2,
         name="misc_0128",
         col=3
      },
      {
         row=3,
         name="misc_0128",
         col=2
      }
   },
   misc_0076={
      {
         row=0,
         name="misc_0075",
         col=0
      },
      {
         row=0,
         name="misc_0075",
         col=1
      },
      {
         row=1,
         name="misc_0075",
         col=0
      },
      {
         row=1,
         name="misc_0075",
         col=1
      }
   },
   misc_0088={
      {
         row=0,
         name="misc_0081",
         col=0
      },
      {
         row=0,
         name="misc_0081",
         col=1
      },
      {
         row=1,
         name="misc_0081",
         col=0
      },
      {
         row=1,
         name="misc_0081",
         col=1
      }
   },
   misc_0132={
      {
         row=0,
         name="misc_0083",
         col=0
      },
      {
         row=0,
         name="misc_0083",
         col=1
      },
      {
         row=1,
         name="misc_0083",
         col=0
      },
      {
         row=1,
         name="misc_0083",
         col=1
      }
   },
   misc_0267={
      {
         row=0,
         name="misc_0263",
         col=0
      },
      {
         row=0,
         name="misc_0263",
         col=1
      },
      {
         row=0,
         name="misc_0263",
         col=2
      },
      {
         row=1,
         name="misc_0263",
         col=0
      },
      {
         row=1,
         name="misc_0263",
         col=2
      },
      {
         row=2,
         name="misc_0263",
         col=0
      },
      {
         row=2,
         name="misc_0263",
         col=1
      },
      {
         row=2,
         name="misc_0263",
         col=2
      }
   },
   misc_seedmia={
      {
         row=0,
         name="misc_0022",
         col=0
      },
      {
         row=0,
         name="misc_0022",
         col=1
      },
      {
         row=1,
         name="misc_0022",
         col=0
      },
      {
         row=1,
         name="misc_0022",
         col=1
      }
   },
   misc_0027={
      {
         row=0,
         name="misc_0012",
         col=0
      },
      {
         row=0,
         name="misc_0012",
         col=1
      },
      {
         row=1,
         name="misc_0012",
         col=2
      },
      {
         row=2,
         name="misc_0012",
         col=1
      },
      {
         row=3,
         name="misc_0012",
         col=1
      }
   },
   misc_0278={
      {
         row=0,
         name="misc_0260",
         col=0
      },
      {
         row=0,
         name="misc_0260",
         col=1
      },
      {
         row=0,
         name="misc_0260",
         col=3
      },
      {
         row=1,
         name="misc_0260",
         col=2
      },
      {
         row=2,
         name="misc_0260",
         col=1
      },
      {
         row=2,
         name="misc_0260",
         col=3
      },
      {
         row=3,
         name="misc_0260",
         col=1
      },
      {
         row=3,
         name="misc_0260",
         col=2
      }
   },
   misc_0260={
      {
         row=0,
         name="misc_0237",
         col=0
      },
      {
         row=0,
         name="misc_0237",
         col=1
      },
      {
         row=0,
         name="misc_0237",
         col=3
      },
      {
         row=1,
         name="misc_0237",
         col=2
      },
      {
         row=2,
         name="misc_0237",
         col=1
      },
      {
         row=2,
         name="misc_0237",
         col=3
      },
      {
         row=3,
         name="misc_0237",
         col=1
      },
      {
         row=3,
         name="misc_0237",
         col=2
      }
   },
   misc_0236={
      {
         row=0,
         name="misc_0232",
         col=0
      },
      {
         row=0,
         name="misc_0232",
         col=1
      },
      {
         row=0,
         name="misc_0232",
         col=3
      },
      {
         row=1,
         name="misc_0232",
         col=2
      },
      {
         row=2,
         name="misc_0232",
         col=1
      },
      {
         row=2,
         name="misc_0232",
         col=3
      },
      {
         row=3,
         name="misc_0232",
         col=1
      },
      {
         row=3,
         name="misc_0232",
         col=2
      }
   },
   misc_quicksilver={
      {
         row=0,
         name="misc_silverbar",
         col=0
      },
      {
         row=0,
         name="misc_silverbar",
         col=1
      },
      {
         row=1,
         name="misc_silverbar",
         col=0
      },
      {
         row=3,
         name="misc_silverbar",
         col=1
      },
      {
         row=2,
         name="misc_silverbar",
         col=2
      }
   },
   misc_0009={
      {
         row=0,
         name="misc_0004",
         col=0
      },
      {
         row=0,
         name="misc_0004",
         col=1
      },
      {
         row=1,
         name="misc_0004",
         col=0
      },
      {
         row=1,
         name="misc_0004",
         col=1
      }
   },
   misc_0221={
      {
         row=0,
         name="misc_0138",
         col=0
      },
      {
         row=0,
         name="misc_0138",
         col=3
      },
      {
         row=1,
         name="misc_0138",
         col=1
      },
      {
         row=1,
         name="misc_0138",
         col=2
      },
      {
         row=2,
         name="misc_0138",
         col=0
      },
      {
         row=2,
         name="misc_0138",
         col=3
      }
   },
   misc_0222={
      {
         row=0,
         name="misc_0149",
         col=0
      },
      {
         row=0,
         name="misc_0149",
         col=1
      },
      {
         row=0,
         name="misc_0149",
         col=3
      },
      {
         row=1,
         name="misc_0149",
         col=2
      },
      {
         row=2,
         name="misc_0149",
         col=1
      },
      {
         row=2,
         name="misc_0149",
         col=3
      },
      {
         row=3,
         name="misc_0149",
         col=1
      },
      {
         row=3,
         name="misc_0149",
         col=2
      }
   },
   misc_0063={
      {
         row=0,
         name="misc_Tontulia",
         col=0
      },
      {
         row=0,
         name="misc_Tontulia",
         col=1
      },
      {
         row=1,
         name="misc_Tontulia",
         col=0
      },
      {
         row=1,
         name="misc_Tontulia",
         col=1
      }
   },
   misc_0229={
      {
         row=0,
         name="misc_0222",
         col=0
      },
      {
         row=0,
         name="misc_0222",
         col=1
      },
      {
         row=0,
         name="misc_0222",
         col=3
      },
      {
         row=1,
         name="misc_0222",
         col=2
      },
      {
         row=2,
         name="misc_0222",
         col=1
      },
      {
         row=2,
         name="misc_0222",
         col=3
      },
      {
         row=3,
         name="misc_0222",
         col=1
      },
      {
         row=3,
         name="misc_0222",
         col=2
      }
   },
   misc_0170={
      {
         row=0,
         name="misc_0152",
         col=0
      },
      {
         row=0,
         name="misc_0152",
         col=2
      },
      {
         row=1,
         name="misc_0152",
         col=0
      },
      {
         row=1,
         name="misc_0152",
         col=1
      },
      {
         row=1,
         name="misc_0152",
         col=2
      },
      {
         row=2,
         name="misc_0152",
         col=0
      },
      {
         row=2,
         name="misc_0152",
         col=2
      }
   },
   misc_0263={
      {
         row=0,
         name="misc_0225",
         col=0
      },
      {
         row=0,
         name="misc_0225",
         col=1
      },
      {
         row=0,
         name="misc_0225",
         col=2
      },
      {
         row=1,
         name="misc_0225",
         col=0
      },
      {
         row=1,
         name="misc_0225",
         col=2
      },
      {
         row=2,
         name="misc_0225",
         col=0
      },
      {
         row=2,
         name="misc_0225",
         col=1
      },
      {
         row=2,
         name="misc_0225",
         col=2
      }
   },
   misc_0269={
      {
         row=0,
         name="misc_0226",
         col=0
      },
      {
         row=1,
         name="misc_0226",
         col=1
      },
      {
         row=1,
         name="misc_0226",
         col=3
      },
      {
         row=2,
         name="misc_0226",
         col=2
      },
      {
         row=2,
         name="misc_0226",
         col=3
      },
      {
         row=3,
         name="misc_0226",
         col=2
      }
   },
   misc_0013={
      {
         row=0,
         name="misc_0008",
         col=0
      },
      {
         row=0,
         name="misc_0008",
         col=1
      },
      {
         row=1,
         name="misc_0008",
         col=0
      },
      {
         row=1,
         name="misc_0008",
         col=1
      }
   },
   misc_0022={
      {
         row=0,
         name="misc_leafly",
         col=0
      },
      {
         row=0,
         name="misc_leafly",
         col=1
      },
      {
         row=0,
         name="misc_leafly",
         col=2
      },
      {
         row=1,
         name="misc_leafly",
         col=0
      },
      {
         row=1,
         name="misc_leafly",
         col=1
      },
      {
         row=1,
         name="misc_leafly",
         col=2
      },
      {
         row=2,
         name="misc_leafly",
         col=0
      },
      {
         row=2,
         name="misc_leafly",
         col=1
      },
      {
         row=2,
         name="misc_leafly",
         col=2
      }
   },
   misc_0171={
      {
         row=0,
         name="misc_Mushroom_boy",
         col=0
      },
      {
         row=0,
         name="misc_Mushroom_boy",
         col=1
      },
      {
         row=1,
         name="misc_Mushroom_boy",
         col=0
      },
      {
         row=1,
         name="misc_Mushroom_boy",
         col=1
      }
   },
   misc_jore15={
      {
         row=0,
         name="misc_jore13",
         col=0
      },
      {
         row=0,
         name="misc_jore13",
         col=1
      },
      {
         row=1,
         name="misc_jore13",
         col=0
      },
      {
         row=1,
         name="misc_jore13",
         col=1
      }
   },
   misc_0215={
      {
         row=0,
         name="misc_0210",
         col=0
      },
      {
         row=0,
         name="misc_0210",
         col=1
      },
      {
         row=2,
         name="misc_0210",
         col=1
      },
      {
         row=3,
         name="misc_0210",
         col=1
      },
      {
         row=3,
         name="misc_0210",
         col=2
      },
      {
         row=4,
         name="misc_0210",
         col=1
      }
   },
   misc_0034={
      {
         row=0,
         name="misc_0019",
         col=0
      },
      {
         row=0,
         name="misc_0019",
         col=1
      },
      {
         row=0,
         name="misc_0019",
         col=2
      },
      {
         row=1,
         name="misc_0019",
         col=0
      },
      {
         row=1,
         name="misc_0019",
         col=1
      },
      {
         row=2,
         name="misc_0019",
         col=0
      }
   },
   misc_Lemuria={
      {
         row=0,
         name="misc_0092",
         col=0
      },
      {
         row=0,
         name="misc_0092",
         col=1
      },
      {
         row=1,
         name="misc_0092",
         col=0
      },
      {
         row=1,
         name="misc_0092",
         col=1
      }
   },
   misc_Hallowventor={
      {
         row=0,
         name="misc_0061",
         col=0
      },
      {
         row=0,
         name="misc_0061",
         col=1
      },
      {
         row=1,
         name="misc_0061",
         col=0
      },
      {
         row=1,
         name="misc_0061",
         col=1
      }
   },
   misc_0062={
      {
         row=0,
         name="misc_0128",
         col=0
      },
      {
         row=0,
         name="misc_0128",
         col=1
      },
      {
         row=1,
         name="misc_0128",
         col=0
      },
      {
         row=1,
         name="misc_0128",
         col=1
      }
   },
   misc_glyquare={
      {
         row=0,
         name="misc_anchor",
         col=0
      },
      {
         row=0,
         name="misc_anchor",
         col=1
      },
      {
         row=1,
         name="misc_anchor",
         col=0
      },
      {
         row=1,
         name="misc_anchor",
         col=1
      }
   },
   misc_velffigy={
      {
         row=0,
         name="misc_0181",
         col=0
      },
      {
         row=0,
         name="misc_0181",
         col=1
      },
      {
         row=1,
         name="misc_0181",
         col=0
      },
      {
         row=1,
         name="misc_0181",
         col=1
      }
   },
   Hat_628042={
      {
         row=0,
         name="wood_01",
         col=0
      },
      {
         row=0,
         name="wood_01",
         col=1
      },
      {
         row=0,
         name="wood_01",
         col=3
      },
      {
         row=0,
         name="wood_01",
         col=4
      },
      {
         row=1,
         name="misc_ore09",
         col=0
      },
      {
         row=1,
         name="misc_Echad3",
         col=1
      },
      {
         row=1,
         name="wood_01",
         col=2
      },
      {
         row=1,
         name="misc_shtayim3",
         col=3
      },
      {
         row=1,
         name="misc_ore09",
         col=4
      },
      {
         row=2,
         name="wood_01",
         col=0
      },
      {
         row=2,
         name="wood_01",
         col=1
      },
      {
         row=2,
         name="wood_01",
         col=3
      },
      {
         row=2,
         name="wood_01",
         col=4
      }
   },
   misc_Tontulia={
      {
         row=0,
         name="misc_Tucen",
         col=0
      },
      {
         row=0,
         name="misc_Tucen",
         col=1
      },
      {
         row=1,
         name="misc_Tucen",
         col=0
      },
      {
         row=1,
         name="misc_Tucen",
         col=1
      }
   },
   misc_0122={
      {
         row=0,
         name="misc_0103",
         col=0
      },
      {
         row=1,
         name="misc_0103",
         col=1
      },
      {
         row=1,
         name="misc_0103",
         col=3
      },
      {
         row=2,
         name="misc_0103",
         col=2
      },
      {
         row=2,
         name="misc_0103",
         col=3
      },
      {
         row=3,
         name="misc_0103",
         col=2
      }
   },
   misc_jore14={
      {
         row=0,
         name="misc_jore12",
         col=0
      }
   },
   misc_0102={
      {
         row=0,
         name="misc_0100",
         col=0
      },
      {
         row=0,
         name="misc_0100",
         col=1
      },
      {
         row=2,
         name="misc_0100",
         col=1
      },
      {
         row=3,
         name="misc_0100",
         col=1
      },
      {
         row=3,
         name="misc_0100",
         col=2
      },
      {
         row=4,
         name="misc_0100",
         col=1
      }
   },
   misc_Fisherman={
      {
         row=0,
         name="misc_Minos1",
         col=0
      },
      {
         row=1,
         name="misc_Minos1",
         col=0
      },
      {
         row=2,
         name="misc_Minos1",
         col=0
      },
      {
         row=3,
         name="misc_Minos1",
         col=0
      }
   },
   misc_0093={
      {
         row=0,
         name="misc_shtayim",
         col=0
      },
      {
         row=0,
         name="misc_shtayim",
         col=1
      },
      {
         row=1,
         name="misc_shtayim",
         col=0
      },
      {
         row=1,
         name="misc_shtayim",
         col=1
      }
   },
   misc_0181={
      {
         row=0,
         name="misc_0175",
         col=0
      },
      {
         row=0,
         name="misc_0175",
         col=1
      },
      {
         row=1,
         name="misc_0175",
         col=0
      },
      {
         row=1,
         name="misc_0175",
         col=1
      }
   },
   misc_0164={
      {
         row=0,
         name="misc_0162",
         col=0
      },
      {
         row=0,
         name="misc_0162",
         col=1
      },
      {
         row=1,
         name="misc_0162",
         col=0
      },
      {
         row=1,
         name="misc_0162",
         col=1
      }
   },
   Drug_HP3={
      {
         row=0,
         name="Drug_HP1",
         col=0
      },
      {
         row=1,
         name="Drug_HP1",
         col=0
      },
      {
         row=0,
         name="Drug_HP2",
         col=1
      }
   },
   misc_mushroom_ent={
      {
         row=0,
         name="misc_Mushroom_boy",
         col=0
      },
      {
         row=0,
         name="misc_Mushroom_boy",
         col=1
      },
      {
         row=1,
         name="misc_Mushroom_boy",
         col=0
      },
      {
         row=1,
         name="misc_Mushroom_boy",
         col=1
      },
      {
         row=2,
         name="misc_Mushroom_boy",
         col=0
      },
      {
         row=2,
         name="misc_Mushroom_boy",
         col=1
      }
   },
   misc_0035={
      {
         row=0,
         name="misc_0112",
         col=0
      },
      {
         row=1,
         name="misc_0112",
         col=0
      },
      {
         row=2,
         name="misc_0112",
         col=0
      }
   },
   misc_0141={
      {
         row=0,
         name="misc_0139",
         col=0
      },
      {
         row=0,
         name="misc_0139",
         col=1
      },
      {
         row=0,
         name="misc_0139",
         col=2
      },
      {
         row=1,
         name="misc_0139",
         col=0
      },
      {
         row=1,
         name="misc_0139",
         col=2
      },
      {
         row=2,
         name="misc_0139",
         col=0
      },
      {
         row=2,
         name="misc_0139",
         col=1
      },
      {
         row=2,
         name="misc_0139",
         col=2
      }
   },
   misc_0008={
      {
         row=0,
         name="misc_0005",
         col=0
      },
      {
         row=0,
         name="misc_0005",
         col=1
      },
      {
         row=1,
         name="misc_0005",
         col=0
      },
      {
         row=1,
         name="misc_0005",
         col=1
      }
   },
   misc_0178={
      {
         row=0,
         name="misc_kowak",
         col=0
      },
      {
         row=0,
         name="misc_kowak",
         col=1
      },
      {
         row=1,
         name="misc_kowak",
         col=0
      },
      {
         row=1,
         name="misc_kowak",
         col=1
      }
   },
   misc_0043={
      {
         row=0,
         name="misc_Corylus",
         col=0
      },
      {
         row=1,
         name="misc_Corylus",
         col=0
      },
      {
         row=2,
         name="misc_Corylus",
         col=0
      }
   },
   misc_0187={
      {
         row=0,
         name="misc_0155",
         col=0
      },
      {
         row=1,
         name="misc_0155",
         col=1
      },
      {
         row=1,
         name="misc_0155",
         col=3
      },
      {
         row=2,
         name="misc_0155",
         col=2
      },
      {
         row=2,
         name="misc_0155",
         col=3
      },
      {
         row=3,
         name="misc_0155",
         col=2
      }
   },
   misc_0138={
      {
         row=0,
         name="misc_0119",
         col=0
      },
      {
         row=0,
         name="misc_0119",
         col=3
      },
      {
         row=1,
         name="misc_0119",
         col=1
      },
      {
         row=1,
         name="misc_0119",
         col=2
      },
      {
         row=2,
         name="misc_0119",
         col=0
      },
      {
         row=2,
         name="misc_0119",
         col=3
      }
   },
   misc_0174={
      {
         row=0,
         name="misc_0172",
         col=0
      },
      {
         row=0,
         name="misc_0172",
         col=1
      },
      {
         row=1,
         name="misc_0172",
         col=0
      },
      {
         row=1,
         name="misc_0172",
         col=1
      }
   },
   misc_0157={
      {
         row=0,
         name="misc_0088",
         col=0
      },
      {
         row=0,
         name="misc_0088",
         col=1
      },
      {
         row=1,
         name="misc_0088",
         col=0
      },
      {
         row=1,
         name="misc_0088",
         col=1
      }
   },
   misc_0168={
      {
         row=0,
         name="misc_0149",
         col=0
      },
      {
         row=0,
         name="misc_0149",
         col=1
      },
      {
         row=1,
         name="misc_0149",
         col=0
      },
      {
         row=1,
         name="misc_0149",
         col=1
      }
   },
   misc_0223={
      {
         row=0,
         name="misc_0187",
         col=0
      },
      {
         row=1,
         name="misc_0187",
         col=1
      },
      {
         row=1,
         name="misc_0187",
         col=3
      },
      {
         row=2,
         name="misc_0187",
         col=2
      },
      {
         row=2,
         name="misc_0187",
         col=3
      },
      {
         row=3,
         name="misc_0187",
         col=2
      }
   },
   misc_0161={
      {
         row=0,
         name="misc_0158",
         col=0
      },
      {
         row=0,
         name="misc_0158",
         col=1
      },
      {
         row=1,
         name="misc_0158",
         col=0
      },
      {
         row=1,
         name="misc_0158",
         col=1
      }
   },
   misc_Mushroom_boy={
      {
         row=0,
         name="misc_0131",
         col=0
      },
      {
         row=0,
         name="misc_0131",
         col=1
      },
      {
         row=0,
         name="misc_0131",
         col=2
      },
      {
         row=1,
         name="misc_0131",
         col=0
      },
      {
         row=1,
         name="misc_0131",
         col=1
      },
      {
         row=1,
         name="misc_0131",
         col=2
      }
   },
   misc_0147={
      {
         row=0,
         name="tree_root_mole1",
         col=0
      },
      {
         row=0,
         name="tree_root_mole1",
         col=1
      },
      {
         row=1,
         name="tree_root_mole1",
         col=0
      },
      {
         row=1,
         name="tree_root_mole1",
         col=1
      }
   },
   misc_0158={
      {
         row=0,
         name="misc_0157",
         col=0
      },
      {
         row=0,
         name="misc_0157",
         col=1
      },
      {
         row=0,
         name="misc_0157",
         col=2
      },
      {
         row=1,
         name="misc_0157",
         col=0
      },
      {
         row=1,
         name="misc_0157",
         col=1
      },
      {
         row=1,
         name="misc_0157",
         col=2
      },
      {
         row=2,
         name="misc_0157",
         col=0
      },
      {
         row=2,
         name="misc_0157",
         col=1
      },
      {
         row=2,
         name="misc_0157",
         col=2
      }
   },
   misc_0165={
      {
         row=0,
         name="misc_0143",
         col=0
      },
      {
         row=0,
         name="misc_0143",
         col=1
      },
      {
         row=1,
         name="misc_0143",
         col=0
      },
      {
         row=1,
         name="misc_0143",
         col=1
      }
   },
   misc_puragi={
      {
         row=0,
         name="misc_0018",
         col=0
      },
      {
         row=1,
         name="misc_0018",
         col=0
      },
      {
         row=2,
         name="misc_0018",
         col=0
      }
   },
   misc_0149={
      {
         row=0,
         name="misc_0147",
         col=0
      },
      {
         row=0,
         name="misc_0147",
         col=1
      },
      {
         row=0,
         name="misc_0147",
         col=3
      },
      {
         row=1,
         name="misc_0147",
         col=2
      },
      {
         row=2,
         name="misc_0147",
         col=1
      },
      {
         row=2,
         name="misc_0147",
         col=3
      },
      {
         row=3,
         name="misc_0147",
         col=1
      },
      {
         row=3,
         name="misc_0147",
         col=2
      }
   },
   misc_0080={
      {
         row=0,
         name="misc_0072",
         col=0
      },
      {
         row=0,
         name="misc_0072",
         col=1
      },
      {
         row=1,
         name="misc_0072",
         col=2
      },
      {
         row=2,
         name="misc_0072",
         col=1
      },
      {
         row=3,
         name="misc_0072",
         col=1
      }
   },
   misc_0041={
      {
         row=0,
         name="misc_0020",
         col=0
      },
      {
         row=0,
         name="misc_0020",
         col=3
      },
      {
         row=1,
         name="misc_0020",
         col=1
      },
      {
         row=1,
         name="misc_0020",
         col=2
      },
      {
         row=2,
         name="misc_0020",
         col=0
      },
      {
         row=2,
         name="misc_0020",
         col=3
      }
   },
   misc_0079={
      {
         row=0,
         name="misc_arburn_pokubu_blue2",
         col=0
      },
      {
         row=0,
         name="misc_arburn_pokubu_blue2",
         col=1
      },
      {
         row=1,
         name="misc_arburn_pokubu_blue2",
         col=0
      },
      {
         row=1,
         name="misc_arburn_pokubu_blue2",
         col=1
      }
   },
   misc_0205={
      {
         row=0,
         name="misc_0201",
         col=0
      },
      {
         row=0,
         name="misc_0201",
         col=1
      },
      {
         row=1,
         name="misc_0201",
         col=2
      },
      {
         row=2,
         name="misc_0201",
         col=1
      },
      {
         row=3,
         name="misc_0201",
         col=1
      }
   },
   misc_0172={
      {
         row=0,
         name="misc_0163",
         col=0
      },
      {
         row=0,
         name="misc_0163",
         col=1
      },
      {
         row=1,
         name="misc_0163",
         col=0
      },
      {
         row=1,
         name="misc_0163",
         col=1
      }
   },
   misc_0156={
      {
         row=0,
         name="misc_0166",
         col=0
      },
      {
         row=0,
         name="misc_0166",
         col=1
      },
      {
         row=1,
         name="misc_0166",
         col=0
      },
      {
         row=1,
         name="misc_0166",
         col=1
      }
   },
   misc_0049={
      {
         row=0,
         name="misc_0041",
         col=0
      },
      {
         row=0,
         name="misc_0041",
         col=3
      },
      {
         row=1,
         name="misc_0041",
         col=1
      },
      {
         row=1,
         name="misc_0041",
         col=2
      },
      {
         row=2,
         name="misc_0041",
         col=0
      },
      {
         row=2,
         name="misc_0041",
         col=3
      }
   },
   misc_0010={
      {
         row=0,
         name="misc_0006",
         col=0
      },
      {
         row=0,
         name="misc_0006",
         col=1
      },
      {
         row=1,
         name="misc_0006",
         col=0
      },
      {
         row=1,
         name="misc_0006",
         col=1
      }
   },
   misc_arburn_pokubu_blue2={
      {
         row=0,
         name="misc_Stoulet",
         col=0
      },
      {
         row=0,
         name="misc_Stoulet",
         col=1
      },
      {
         row=1,
         name="misc_Stoulet",
         col=0
      },
      {
         row=1,
         name="misc_Stoulet",
         col=1
      }
   },
   misc_0083={
      {
         row=0,
         name="misc_0018",
         col=0
      },
      {
         row=0,
         name="misc_0018",
         col=1
      },
      {
         row=2,
         name="misc_0018",
         col=1
      },
      {
         row=3,
         name="misc_0018",
         col=1
      },
      {
         row=3,
         name="misc_0018",
         col=2
      },
      {
         row=4,
         name="misc_0018",
         col=1
      }
   },
   misc_0128={
      {
         row=0,
         name="misc_0122",
         col=0
      },
      {
         row=1,
         name="misc_0122",
         col=1
      },
      {
         row=1,
         name="misc_0122",
         col=3
      },
      {
         row=2,
         name="misc_0122",
         col=2
      },
      {
         row=2,
         name="misc_0122",
         col=3
      },
      {
         row=3,
         name="misc_0122",
         col=2
      }
   },
   misc_0216={
      {
         row=0,
         name="misc_0212",
         col=0
      },
      {
         row=0,
         name="misc_0212",
         col=1
      },
      {
         row=1,
         name="misc_0212",
         col=2
      },
      {
         row=2,
         name="misc_0212",
         col=1
      },
      {
         row=3,
         name="misc_0212",
         col=1
      }
   },
   misc_0109={
      {
         row=0,
         name="misc_0049",
         col=0
      },
      {
         row=0,
         name="misc_0049",
         col=3
      },
      {
         row=1,
         name="misc_0049",
         col=1
      },
      {
         row=1,
         name="misc_0049",
         col=2
      },
      {
         row=2,
         name="misc_0049",
         col=0
      },
      {
         row=2,
         name="misc_0049",
         col=3
      }
   },
   misc_0100={
      {
         row=0,
         name="misc_0083",
         col=0
      },
      {
         row=0,
         name="misc_0083",
         col=1
      },
      {
         row=2,
         name="misc_0083",
         col=1
      },
      {
         row=3,
         name="misc_0083",
         col=1
      },
      {
         row=3,
         name="misc_0083",
         col=2
      },
      {
         row=4,
         name="misc_0083",
         col=1
      }
   },
   misc_galok={
      {
         row=0,
         name="misc_Mentiwood",
         col=0
      },
      {
         row=0,
         name="misc_Mentiwood",
         col=1
      },
      {
         row=1,
         name="misc_Mentiwood",
         col=0
      },
      {
         row=1,
         name="misc_Mentiwood",
         col=1
      }
   },
   misc_0143={
      {
         row=0,
         name="misc_0134",
         col=0
      },
      {
         row=0,
         name="misc_0134",
         col=1
      },
      {
         row=1,
         name="misc_0134",
         col=0
      },
      {
         row=1,
         name="misc_0134",
         col=1
      }
   },
   misc_Armory={
      {
         row=0,
         name="misc_rublem",
         col=0
      },
      {
         row=0,
         name="misc_rublem",
         col=1
      },
      {
         row=1,
         name="misc_rublem",
         col=0
      },
      {
         row=1,
         name="misc_rublem",
         col=1
      }
   },
   misc_Minos1={
      {
         row=0,
         name="misc_Lizardman",
         col=0
      },
      {
         row=0,
         name="misc_Lizardman",
         col=1
      },
      {
         row=1,
         name="misc_Lizardman",
         col=0
      },
      {
         row=1,
         name="misc_Lizardman",
         col=1
      }
   },
   misc_0175={
      {
         row=0,
         name="misc_0130",
         col=0
      },
      {
         row=0,
         name="misc_0130",
         col=1
      },
      {
         row=1,
         name="misc_0130",
         col=2
      },
      {
         row=2,
         name="misc_0130",
         col=1
      },
      {
         row=3,
         name="misc_0130",
         col=1
      }
   },
   misc_hanaming2={
      {
         row=0,
         name="leaf_hanaming",
         col=0
      },
      {
         row=0,
         name="leaf_hanaming",
         col=4
      },
      {
         row=1,
         name="leaf_hanaming",
         col=1
      },
      {
         row=1,
         name="leaf_hanaming",
         col=3
      },
      {
         row=2,
         name="leaf_hanaming",
         col=2
      }
   },
   misc_0018={
      {
         row=0,
         name="misc_0014",
         col=0
      },
      {
         row=0,
         name="misc_0014",
         col=1
      },
      {
         row=1,
         name="misc_0014",
         col=0
      },
      {
         row=1,
         name="misc_0014",
         col=1
      },
      {
         row=2,
         name="misc_0014",
         col=0
      },
      {
         row=2,
         name="misc_0014",
         col=1
      }
   },
   misc_0059={
      {
         row=0,
         name="misc_0025",
         col=0
      },
      {
         row=0,
         name="misc_0025",
         col=1
      },
      {
         row=1,
         name="misc_0025",
         col=0
      },
      {
         row=1,
         name="misc_0025",
         col=1
      }
   },
   misc_0152={
      {
         row=0,
         name="misc_0134",
         col=0
      },
      {
         row=1,
         name="misc_0134",
         col=1
      },
      {
         row=1,
         name="misc_0134",
         col=3
      },
      {
         row=2,
         name="misc_0134",
         col=2
      },
      {
         row=2,
         name="misc_0134",
         col=3
      },
      {
         row=3,
         name="misc_0134",
         col=2
      }
   },
   misc_0081={
      {
         row=0,
         name="misc_0100",
         col=0
      },
      {
         row=0,
         name="misc_0100",
         col=1
      },
      {
         row=1,
         name="misc_0100",
         col=0
      },
      {
         row=1,
         name="misc_0100",
         col=1
      }
   },
   misc_Mentiwood={
      {
         row=0,
         name="misc_0040",
         col=0
      },
      {
         row=0,
         name="misc_0040",
         col=1
      },
      {
         row=1,
         name="misc_0040",
         col=0
      },
      {
         row=1,
         name="misc_0040",
         col=1
      }
   },
   misc_0212={
      {
         row=0,
         name="misc_0176",
         col=0
      },
      {
         row=0,
         name="misc_0176",
         col=1
      },
      {
         row=1,
         name="misc_0176",
         col=2
      },
      {
         row=2,
         name="misc_0176",
         col=1
      },
      {
         row=3,
         name="misc_0176",
         col=1
      }
   },
   misc_0104={
      {
         row=0,
         name="misc_0062",
         col=0
      },
      {
         row=0,
         name="misc_0062",
         col=1
      },
      {
         row=1,
         name="misc_0062",
         col=0
      },
      {
         row=1,
         name="misc_0062",
         col=1
      }
   },
   misc_0153={
      {
         row=0,
         name="misc_0055",
         col=0
      },
      {
         row=0,
         name="misc_0055",
         col=1
      },
      {
         row=1,
         name="misc_0055",
         col=0
      },
      {
         row=1,
         name="misc_0055",
         col=1
      }
   },
   misc_0092={
      {
         row=0,
         name="misc_0178",
         col=0
      },
      {
         row=0,
         name="misc_0178",
         col=1
      },
      {
         row=1,
         name="misc_0178",
         col=0
      },
      {
         row=1,
         name="misc_0178",
         col=1
      }
   },
   misc_0037={
      {
         row=0,
         name="misc_humming_bud",
         col=0
      },
      {
         row=0,
         name="misc_humming_bud",
         col=1
      },
      {
         row=1,
         name="misc_humming_bud",
         col=0
      },
      {
         row=1,
         name="misc_humming_bud",
         col=1
      }
   },
   misc_0044={
      {
         row=0,
         name="misc_0043",
         col=0
      },
      {
         row=0,
         name="misc_0043",
         col=1
      },
      {
         row=1,
         name="misc_0043",
         col=0
      },
      {
         row=1,
         name="misc_0043",
         col=1
      }
   },
   misc_0016={
      {
         row=0,
         name="misc_0008",
         col=0
      },
      {
         row=0,
         name="misc_0008",
         col=1
      },
      {
         row=1,
         name="misc_0008",
         col=0
      },
      {
         row=1,
         name="misc_0008",
         col=1
      },
      {
         row=2,
         name="misc_0008",
         col=0
      },
      {
         row=2,
         name="misc_0008",
         col=1
      }
   },
   misc_Cockatries={
      {
         row=0,
         name="misc_0140",
         col=0
      },
      {
         row=0,
         name="misc_0140",
         col=1
      },
      {
         row=1,
         name="misc_0140",
         col=0
      },
      {
         row=1,
         name="misc_0140",
         col=1
      }
   },
   misc_rublem={
      {
         row=0,
         name="misc_Bume_Goblin",
         col=0
      },
      {
         row=0,
         name="misc_Bume_Goblin",
         col=1
      },
      {
         row=1,
         name="misc_Bume_Goblin",
         col=0
      },
      {
         row=1,
         name="misc_Bume_Goblin",
         col=1
      }
   },
   misc_Sakmoli={
      {
         row=0,
         name="misc_0047",
         col=0
      },
      {
         row=0,
         name="misc_0047",
         col=1
      },
      {
         row=1,
         name="misc_0047",
         col=0
      },
      {
         row=1,
         name="misc_0047",
         col=1
      },
      {
         row=2,
         name="misc_0047",
         col=0
      },
      {
         row=2,
         name="misc_0047",
         col=1
      }
   },
   misc_0047={
      {
         row=0,
         name="misc_0034",
         col=0
      },
      {
         row=1,
         name="misc_0034",
         col=1
      },
      {
         row=1,
         name="misc_0034",
         col=3
      },
      {
         row=2,
         name="misc_0034",
         col=2
      },
      {
         row=2,
         name="misc_0034",
         col=3
      },
      {
         row=3,
         name="misc_0034",
         col=2
      }
   },
   misc_Grummer={
      {
         row=0,
         name="misc_0010",
         col=0
      },
      {
         row=0,
         name="misc_0010",
         col=1
      },
      {
         row=1,
         name="misc_0019",
         col=0
      },
      {
         row=1,
         name="misc_0019",
         col=1
      }
   },
   misc_Stoulet={
      {
         row=0,
         name="misc_0155",
         col=0
      },
      {
         row=0,
         name="misc_0155",
         col=1
      },
      {
         row=1,
         name="misc_0155",
         col=0
      },
      {
         row=1,
         name="misc_0155",
         col=1
      }
   },
   misc_0226={
      {
         row=0,
         name="misc_0223",
         col=0
      },
      {
         row=1,
         name="misc_0223",
         col=1
      },
      {
         row=1,
         name="misc_0223",
         col=3
      },
      {
         row=2,
         name="misc_0223",
         col=2
      },
      {
         row=2,
         name="misc_0223",
         col=3
      },
      {
         row=3,
         name="misc_0223",
         col=2
      }
   },
   misc_Lizardman={
      {
         row=0,
         name="misc_0070",
         col=0
      },
      {
         row=1,
         name="misc_0070",
         col=0
      },
      {
         row=2,
         name="misc_0070",
         col=0
      }
   },
   misc_Tucen={
      {
         row=0,
         name="misc_0056",
         col=0
      },
      {
         row=0,
         name="misc_0056",
         col=1
      },
      {
         row=1,
         name="misc_0056",
         col=0
      },
      {
         row=1,
         name="misc_0056",
         col=1
      }
   },
   misc_0065={
      {
         row=0,
         name="misc_Karas",
         col=0
      },
      {
         row=0,
         name="misc_Karas",
         col=1
      },
      {
         row=1,
         name="misc_Karas",
         col=0
      },
      {
         row=1,
         name="misc_Karas",
         col=1
      }
   },
   misc_0105={
      {
         row=0,
         name="misc_Hallowventor",
         col=0
      },
      {
         row=0,
         name="misc_Hallowventor",
         col=1
      },
      {
         row=1,
         name="misc_Hallowventor",
         col=0
      },
      {
         row=1,
         name="misc_Hallowventor",
         col=1
      }
   },
   misc_0015={
      {
         row=0,
         name="misc_0016",
         col=0
      },
      {
         row=0,
         name="misc_0016",
         col=1
      },
      {
         row=1,
         name="misc_0016",
         col=0
      },
      {
         row=1,
         name="misc_0016",
         col=1
      }
   },
   misc_0179={
      {
         row=0,
         name="misc_0176",
         col=0
      },
      {
         row=1,
         name="misc_0176",
         col=0
      },
      {
         row=2,
         name="misc_0176",
         col=0
      },
      {
         row=3,
         name="misc_0176",
         col=0
      }
   },
   misc_anchor={
      {
         row=0,
         name="misc_0173",
         col=0
      },
      {
         row=0,
         name="misc_0173",
         col=1
      },
      {
         row=1,
         name="misc_0173",
         col=0
      },
      {
         row=1,
         name="misc_0173",
         col=1
      }
   },
   misc_0075={
      {
         row=0,
         name="misc_0070",
         col=0
      },
      {
         row=0,
         name="misc_0070",
         col=1
      },
      {
         row=1,
         name="misc_0070",
         col=0
      },
      {
         row=1,
         name="misc_0070",
         col=1
      }
   }
}
return tooltiphelper_magnumopus;